title: Exploring SreeHarsha
author: nanoharsha
email: sreeharsha@hey.com
description: > # this means to ignore newlines until "baseurl:"
  Understanding the basics of github workflow so that I can get my hands dirty and start diving in more deep in the world of opensource.

# social links
twitter_username: nanoharsha
github_username:  nanoharsha

show_excerpts: true # set to false to remove excerpts on the homepage
